export const ChatListData = [
  {
    room_id: 1,
    user_name: '정만월 사장님',
    last_chat_comment: '어딘데 출근 안하니, 죽고싶니?',
    last_chat_time: '2022-03-10T09:32:33',
    profile_img_path: "",
    is_read: false,
    unread_cnt: 2,
  },{
    room_id: 2,
    user_name: '신정근 바텐더',
    last_chat_comment: '오시는 길에 와인 몇병만 사다주세요',
    last_chat_time: '2022-03-10T10:34:33',
    profile_img_path: "",
    is_read: false,
    unread_cnt: 1,
  },
  {
    room_id: 3,
    user_name: '이미라 의사',
    last_chat_comment: '휴가 잘 보내고 계신가요? 다름이 아니라 지금 급한 업무가 생겼는데 바로 전화 부탁드릴게요 ㅜ',
    last_chat_time: '2022-03-09T09:32:33',
    profile_img_path: "",
    is_read: true,
    unread_cnt: 0,
  },
  {
    room_id: 4,
    user_name: '구찬성 지배인',
    last_chat_comment: '아 휴가셨군요. 약속은 다음으로 미루시죠!',
    last_chat_time: '2022-03-09T09:32:33',
    profile_img_path: "",
    is_read: true,
    unread_cnt: 0,
  },
  {
    room_id: 5,
    user_name: '노준석 총지배인',
    last_chat_comment: '휴가에서 언제 돌아오시는지요. 돌아오시면 차 한잔 하실까요?',
    last_chat_time: '2022-03-09T09:32:33',
    profile_img_path: "",
    is_read: true,
    unread_cnt: 0,
  },
  {
    room_id: 6,
    user_name: '김유나 인턴',
    last_chat_comment: '304호 키를 잃어버렸어요 어떻게 해야하죠 ㅠ',
    last_chat_time: '2022-03-08T09:32:33',
    profile_img_path: "",
    is_read: true,
    unread_cnt: 0,
  },
  {
    room_id: 7,
    user_name: '구현모',
    last_chat_comment: '술먹자',
    last_chat_time: '2022-03-07T09:32:33',
    profile_img_path: "",
    is_read: true,
    unread_cnt: 0,
  },

];

export const ChatViewData = [
  {
    room_id: 1,
    chat_view: [
      { 
        chat_id: 32,
        sender_type: 'user',
        user_name: '정만월 사장님',
        send_message_type: 'text',
        send_message: "출근했니?",
        send_time: "2022-03-09T02:34:33",
      },
      { 
        chat_id: 33,
        sender_type: 'user',
        user_name: '정만월 사장님',
        send_message_type: 'text',
        send_message: "출근했냐구?",
        send_time: "2022-03-09T02:35:30",
      },
      { 
        chat_id: 34,
        sender_type: 'user',
        user_name: '정만월 사장님',
        send_message_type: 'text',
        send_message: "어딘데 출근 안하니?",
        send_time: "2022-03-10T02:36:33",
      },
      { 
        chat_id: 364,
        sender_type: 'admin',
        user_name: '정만월 사장님',
        send_message_type: 'text',
        send_message: "해외 출장중입니다.",
        send_time: "2022-03-10T02:37:33",
      },
      { 
        chat_id: 365,
        sender_type: 'admin',
        user_name: '정만월 사장님',
        send_message_type: 'text',
        send_message: "해외 출장중입니다.",
        send_time: "2022-03-10T02:37:34",
      },
      { 
        chat_id: 363,
        sender_type: 'admin',
        user_name: '정만월 사장님',
        send_message_type: 'text',
        send_message: "해외 출장중입니다.",
        send_time: "2022-03-10T02:37:30",
      },
      { 
        chat_id: 366,
        sender_type: 'admin',
        user_name: '정만월 사장님',
        send_message_type: 'text',
        send_message: "해외 출장중입니다.",
        send_time: "2022-03-10T02:38:33",
      },
      { 
        chat_id: 367,
        sender_type: 'admin',
        user_name: '정만월 사장님',
        send_message_type: 'text',
        send_message: "해외 출장중입니다.",
        send_time: "2022-03-10T02:38:33",
      },
      { 
        chat_id: 368,
        sender_type: 'admin',
        user_name: '정만월 사장님',
        send_message_type: 'text',
        send_message: "해외 출장중입니다.",
        send_time: "2022-03-10T02:38:33",
      },
      { 
        chat_id: 369,
        sender_type: 'admin',
        user_name: '정만월 사장님',
        send_message_type: 'text',
        send_message: "해외 출장중입니다.",
        send_time: "2022-03-10T02:38:33",
      },
      { 
        chat_id: 360,
        sender_type: 'admin',
        user_name: '정만월 사장님',
        send_message_type: 'text',
        send_message: "해외 출장중입니다.",
        send_time: "2022-03-10T02:38:33",
      },
    ]
  },
  {
    room_id: 2,
    chat_view: [
      { 
        chat_id: 33,
        sender_type: 'user',
        user_name: '신정근 바텐더',
        send_message_type: 'text',
        send_message: "오시는길에 와인 몇병만 사다주세요",
        send_time: "2022-03-09T02:34:33",
      },
    ]
  }
];